export const SELECT_EMPLOYEE = "SELECT_EMPLOYEE";
export const UNSELECT_EMPLOYEE = "UNSELECT_EMPLOYEE";
export const SAVE_FETCHED_EMPLOYEES = "SAVE_FETCHED_EMPLOYEES";
export const GET_EMPLOYEES = "GET_EMPLOYEES";
